# Generated by Django 4.2.9 on 2024-11-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_staffaccount_user'),
    ]
    operations = [
        migrations.AddField(
            model_name='assessment',
            name='out_of',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schoolsetting',
            name='school_name',
            field=models.CharField(max_length=50),
        ),
    ]
