# Generated by Django 4.2.9 on 2024-11-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_assessment_out_of_alter_schoolsetting_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsetting',
            name='school_name',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
