# Generated by Django 4.2.9 on 2024-11-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_schoolsetting_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='out_of',
            field=models.IntegerField(default=100),
        ),
    ]
