# Generated by Django 4.2.9 on 2024-11-25 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_assessment_out_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot', models.IntegerField(default=0)),
                ('mot', models.IntegerField(default=0)),
                ('eot', models.IntegerField(default=0)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_results', to='app.academicclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
            ],
        ),
    ]
