# Generated by Django 4.2.9 on 2024-12-12 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_reportresults'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportresults',
            name='academic_class',
        ),
        migrations.RemoveField(
            model_name='reportresults',
            name='student',
        ),
        migrations.RemoveField(
            model_name='reportresults',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='is_done',
        ),
        migrations.DeleteModel(
            name='AnnualResult',
        ),
        migrations.DeleteModel(
            name='ReportResults',
        ),
    ]
