# Generated by Django 4.2.9 on 2024-12-12 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_reportresults_academic_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ReportResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot', models.IntegerField(default=0)),
                ('mot', models.IntegerField(default=0)),
                ('eot', models.IntegerField(default=0)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_results', to='app.academicclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject')),
            ],
        ),
        migrations.CreateModel(
            name='AnnualResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('average_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('rank_in_class', models.IntegerField(blank=True, null=True)),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_results', to='app.academicclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_results', to='app.student')),
            ],
        ),
    ]
