# Generated by Django 4.2.9 on 2025-05-21 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_merge_20250521_0948'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budgetitem',
            unique_together={('budget', 'department', 'expense')},
        ),
    ]
