# Generated by Django 5.2.3 on 2025-06-27 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_role_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportresults',
            name='bot',
        ),
        migrations.RemoveField(
            model_name='reportresults',
            name='eot',
        ),
        migrations.RemoveField(
            model_name='reportresults',
            name='mot',
        ),
        migrations.AddField(
            model_name='reportresults',
            name='term',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.term'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='assessment_method',
            field=models.CharField(choices=[('CUMULATIVE', 'Cumulative'), ('NON_CUMULATIVE', 'Non-Cumulative')], default='CUMULATIVE', max_length=15),
        ),
        migrations.CreateModel(
            name='ReportResultDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('points', models.DecimalField(decimal_places=2, max_digits=4)),
                ('assessment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.assessmenttype')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='app.reportresults')),
            ],
        ),
    ]
