# Generated by Django 5.2.3 on 2025-07-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_remove_reportresults_bot_remove_reportresults_eot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultModeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('CUMULATIVE', 'Cumulative'), ('NON_CUMULATIVE', 'Non-Cumulative')], default='CUMULATIVE', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='schoolsetting',
            name='assessment_method',
        ),
    ]
