# Generated by Django 5.2.3 on 2025-08-09 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_resultmodesetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsetting',
            name='email',
            field=models.EmailField(blank=True, help_text='Official school email address', max_length=254, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
