# Generated by Django 5.2.3 on 2025-08-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_schoolsetting_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicclassstream',
            name='class_teacher_signature',
            field=models.ImageField(default='', upload_to='signatures'),
            preserve_default=False,
        ),
    ]
