# Generated by Django 5.2.3 on 2025-09-06 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_signature_position_reportremark'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('applied_date', models.DateField(blank=True, null=True)),
                ('is_applied', models.BooleanField(default=False)),
                ('applied_to_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_credits', to='app.studentbill')),
                ('original_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_credits', to='app.studentbill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='app.student')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
