# Generated by Django 5.2.3 on 2025-12-24 23:01

import app.models.staffs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_alter_staffdocument_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='nin_no',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[app.models.staffs.validate_nin]),
        ),
    ]
