# Generated by Django 4.2.9 on 2026-02-11 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0058_announcement_created_by_event_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='audience',
            field=models.CharField(choices=[('all', 'All Staff'), ('teachers', 'Teachers'), ('head', 'Head Teacher'), ('bursar', 'Bursar'), ('dos', 'Director of Studies'), ('class_teacher', 'Class Teacher'), ('class_stream', 'Class Stream Teachers')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='audience',
            field=models.CharField(choices=[('all', 'All Staff'), ('teachers', 'Teachers'), ('head', 'Head Teacher'), ('bursar', 'Bursar'), ('dos', 'Director of Studies'), ('class_teacher', 'Class Teacher'), ('class_stream', 'Class Stream Teachers')], default='all', max_length=20),
        ),
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_threads', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='message_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.messagethread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='app.announcement')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeted_announcements', to='app.staff')),
            ],
            options={
                'unique_together': {('announcement', 'staff')},
            },
        ),
    ]
