# Generated by Django 4.2.9 on 2026-02-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_message_thread_archive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['start_time', 'end_time', 'id']},
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='division_critical_subjects',
            field=models.ManyToManyField(blank=True, help_text="Subjects that can lower a student's division if grade is F9.", related_name='division_critical_for', to='app.subject'),
        ),
        migrations.AddField(
            model_name='schoolsetting',
            name='division_f9_cap',
            field=models.CharField(default='Division 3', help_text='Maximum division allowed when a critical subject has F9 (e.g., Division 2 or Division 3).', max_length=12),
        ),
    ]
