# Generated by Django 4.2.9 on 2026-02-16 13:51

from django.db import migrations
from django.db.models import Count, Max


def dedupe_class_subject_allocations(apps, schema_editor):
    ClassSubjectAllocation = apps.get_model("app", "ClassSubjectAllocation")
    duplicate_groups = (
        ClassSubjectAllocation.objects.values("academic_class_stream_id", "subject_id")
        .annotate(row_count=Count("id"), keep_id=Max("id"))
        .filter(row_count__gt=1)
    )

    for group in duplicate_groups:
        (
            ClassSubjectAllocation.objects.filter(
                academic_class_stream_id=group["academic_class_stream_id"],
                subject_id=group["subject_id"],
            )
            .exclude(id=group["keep_id"])
            .delete()
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_attendancesession_attendancerecord'),
    ]

    operations = [
        migrations.RunPython(dedupe_class_subject_allocations, noop_reverse),
        migrations.AlterUniqueTogether(
            name='classsubjectallocation',
            unique_together={('academic_class_stream', 'subject')},
        ),
    ]
