# Generated by Django 4.2.9 on 2026-02-16 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_attendancesession_attendancerecord'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classsubjectallocation',
            unique_together={('academic_class_stream', 'subject')},
        ),
    ]
