from .classes import *
from .students import *
from .fees_payment import *
from .school_settings import *
from .subjects import *
from .staffs import *
from .finance import *
from .accounts import *
from .results import *
from .timetables import *
from .audit import *
